### ISSUE TITLE
Wall-E Containerize for github/resqued

### ISSUE THREAD

**Issue by wenlock** [spraints/resqued#56]
# Wall-E #3 Containerize Services

👋🏼 Greetings, fellow Hubbers. We're knocking on your door because the service(s) in this repo have been selected for containerization for GHPI! 🎉

### Why me?

- Short answer: All services that run on GHES need to be containerized for scalability + GHPI purposes. 
- Long answer: [Containerize all the things for GHPI](https://github.com/github/wall-e/blob/master/inner-loop-and-testing/3-build-all-services-on-standardized-containers/project-plan.md#problem-statement)

### How do I containerize my service?

- [ ] Follow the [Containerization Guide](https://github.com/github/containers-for-all/tree/main/docs) to containerize your service.
- [ ] Follow the steps in the [Nomad integration guide](https://github.com/github/ghes-infrastructure/blob/master/docs/nomad-containers/nomad-integration-guide.md) to make sure your container will run on GHES/GHPI.

### How long will it take?

Our best guess right now is **3 weeks** for **1 developer**. But we don't have data to support this yet. It will likely be shorter for some teams/services, and longer for others. We'll update estimates as results come in.

### When does it need to be done by?

- Short answer: **ASAP**
- Long answer: Containerizing is one of the highest priority Wall-E streams (and is formally higher priority than other Wall-E fan-out requests), because we will not be able to effectively deliver many services for GHES/GHPI until this work is done. Please prioritize this as high on your list as you can. Reach out to us if you need to discuss and we can help escalate if need be.

### Need support?

- Follow our [Support Guide](https://github.com/github/wall-e/tree/master/inner-loop-and-testing/3-build-all-services-on-standardized-containers/fan-out-support-guide.md) for more detail.
- Create an issue in [github/containers-for-all](https://github.com/github/containers-for-all/issues/new)
- For quick questions or to escalate, find us in [#wall-e-containers-for-all](https://github.slack.com/archives/C0160STFHHN)
- Drop in on our [office hours](https://github.com/github/wall-e/blob/master/inner-loop-and-testing/3-build-all-services-on-standardized-containers/README.md#connect)

### FAQ

Visit the full [FAQ](https://github.com/github/containers-for-all/blob/main/docs/FAQ.md) for more questions and answers.

#### Does my container need to work with GitHub.com?  What about GHES?

Not as part of this request.  In the future we think it would be great to build each product once in a way that it can be deployed anywhere, but that involves more challenges and more work than we can handle during Wall-E.

#### What is GHPI?

We're glad you asked!  At a very high level, [GHPI](https://github.com/github/ghpi/blob/master/strategy.md) is a GitHub-managed instance of GitHub Enterprise, hosted in the cloud.  With GHPI we can reduce customers' maintenance costs while still providing the additional security that customers enjoy expect from GitHub Enterprise.

#### What if my service is already containerized?

There are differences between a docker container built for GHES and the one being built for GHPI, with the primary difference being the explicit base and builder images that we're asking teams to use. We're also asking folks to follow a specific process to build and push their containers into a specific location.

You will likely be able to reuse any Nomad config that exists in GHES (likely in github/enterprise2), though we're also asking teams to bring that config into their repos.

See the [Containerization Guide](https://github.com/github/containers-for-all/tree/main/docs) for more information about all of the above.

/cc @github/wall-e-standardized-containers

- [Tracking issue in `github/containers-for-all`](https://github.com/github/containers-for-all/issues/56)

**Comment by glortho** [comment]
👋 Howdy folks -- @c-brooks and I will be your points of contact for this work to help answer questions and unblock you best we can. Let's use this issue for initial conversations and statuses, but our team at[#wall-e-containers-for-all](https://github.slack.com/archives/C0160STFHHN) may be better suited than we to answer weedy technical questions. Do not hesitate to visit us there to escalate/expedite.

/cc @rafer as service owner for visibility given high priority (Hello again Rafer! 😄)
